RepoName: aliyun-computenest/quickstart-openhands
DockerComposeEnvPath: ''
RunCommand: |-
  docker pull docker.all-hands.dev/all-hands-ai/runtime:0.47-nikolaik

  docker run -it --rm --pull=always \
      -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.47-nikolaik \
      -e LOG_ALL_EVENTS=true \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v ~/.openhands:/.openhands \
      -p 3000:3000 \
      --add-host host.docker.internal:host-gateway \
      --name openhands-app \
      docker.all-hands.dev/all-hands-ai/openhands:0.47
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- '3000'
RuntimeType: LinuxShell
DockerFilePath: ''
ServicePorts:
- '3000'
ServiceType: private
ArtifactSourceType: SourceCode
ServiceBuildRegion: ap-southeast-1
ImageId: '"{{resolve:oos:aliyun/services/ecs/images/linux/aliyun-latest/alibaba_cloud_linux_3_2104_lts_x64}}"'
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: ''
Owner: hanans426
Branch: main
Platform: github
